spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/flightdb
    username: root
    password: root

logging:
  level:
    root: info
    com.ding.airlinewebservice: debug

# ALL < trace < debug < info < warn < error < fatal
